### ISSUE TITLE
Drawings with Schamatic reference designators

### ISSUE THREAD

**Issue by gvoigtlaender** [dsaltas/WiFi-WebRadio#2]
Could you provide a rendered drawing including the referenced parts of Schamatic (e.g. R5, C8, ...)? I got my pcbs from OSH Park + lots of SMDs, but it is hard to pick correct parts with Schematic only

Thanks

**Comment by dsaltas** [comment]
Hello gvoigtlaender,

Thank you for your interest. You can download EAGLE (https://www.autodesk.com/products/eagle/free-download) and open the file WiFiRadio.brd (under Hardware folder). You will find all the reference designators there. Good luck with your build!

**Comment by dsaltas** [comment]
Reference designators files added under hardware directory.

**Comment by gvoigtlaender** [comment]
Thank you very much
